xcodebuild_arguments: [-workspace, WebexSDK.xcworkspace, -scheme, WebexSDK, -configuration, Debug, CODE_SIGNING_ALLOWED=NO, -sdk, iphoneos]
module: WebexSDK
clean: true
author: Cisco Systems, Inc.
author_url: https://developer.webex.com
github_url: https://github.com/webex/webex-ios-sdk
output: Docs
#min_acl: private
#source_directory: ../source/
#module: SparkBnB
